### ISSUE TITLE
Changing backgrounds

### ISSUE THREAD

**Issue by annopackage** [njanakiev/blender-scripting-intro#8]
Hi, thanks for this amazing project. I want to change the background image of the render animations as follows:

  filepath = "ground.jpeg"
  img = bpy.data.images.load(filepath)
  cam = bpy.context.scene.camera
  cam.data.show_background_images = True
  bg = cam.data.background_images.new()
  bg.image = img

But it doesn't work. I only know how to change the color of background now. Could you help me fix this?

**Comment by njanakiev** [comment]
Thanks for the issue @annopackage. This won't be supported for now, but it would be an interesting question for the Blender Stack Exchange (https://blender.stackexchange.com/) and might help other people with this problem.
